### ISSUE TITLE
Show to Players (Suggestion)

### ISSUE THREAD

**Issue by SoilentBrad** [BluSunrize/fvtt-clockworks#1]
Hey! I've been looking for something like this for a while. I was wondering if there were a way to show to players. I'd like my players to see it for a countdown to increase tension as it goes.

**Comment by davidhawbecker** [comment]
I was coming here just to recommend this very same feature. I love this mod for tracking various things and there are times when I want to show my players the clock on their screen. I notice you can pop it out. Just wondering if there's a way to add a show to players button at the top, like journals. Either way great work and thank you for sharing.

**Comment by BluSunrize** [comment]
All of this is now available in release 1.2.0!

**Comment by davidhawbecker** [comment]
Amazing! Such a great qol. Thank you for the great work.
