### ISSUE TITLE
(Minor Bug) Scroll bar resets at top every time you add or subtract time from a clock at the bottom.

### ISSUE THREAD

**Issue by davidhawbecker** [BluSunrize/fvtt-clockworks#3]
I've created 15 clocks for various trackers, which means you need to scroll down the list to see the ones at the bottom. When you add or subtract time from the clocks at the bottom it resets the scroll bar to the top of the page  and you need to scroll back down to add of subtract from any clocks at the bottom. 

Also on a related note, if it's possible it would be nice to be able to drag or somehow resort the clocks once they're created. 

Still an awesome tool. Thanks again for the work.

**Comment by BluSunrize** [comment]
All of this is now fixed & available in release 1.2.0!
