### ISSUE TITLE
Ability to Hide a Clock [Suggestion]

### ISSUE THREAD

**Issue by Willowlark** [BluSunrize/fvtt-clockworks#5]
I love the functionality of this implementation of Clocks and how much you can customize those clocks. I have run into the case where I wanted to make a customized clock using images and such, but the clock would spoil an encounter later in the session if I left it in the tracker. Is there any chance the ability to hide clocks from players could be added, so that you can pre setup clocks?

**Comment by BluSunrize** [comment]
That's already a feature in the current release! See the Changelog for v 1.3.0:

> * Change ownership behavior:
>    * "Limited" means users can see the clock, but the name is obfuscated
>    * "Obeserver" means the users can see the name of the clock as well
>    * "Owner" means the clock can be incremented, decremented and edited
> * Add a config option for the default ownership of a newly

https://github.com/BluSunrize/fvtt-clockworks/releases/tag/1.3.0

**Comment by BluSunrize** [comment]
Sorry, I should add to this:

"None" makes the clock fully invisible to players (since that is what you asked for ^^)
